name: Coding Standards

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.1']
    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: json
          coverage: xdebug

      - name: Install Composer dependencies
        run: |
          composer update --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: PHP-CS-FIXER
        run: make ci-cs
